action/disasterr/add_disaster.php
modal/disaster.php
admin_page/brgy_record.php
admin_page/confidence_analysis.php
admin_page/predictive.
scripts/auth_script/ocr.js
admin_page/brgy_record.php
database/ecryption.php
ECRYPTION_README.md
action/auth_action/user_pre_reg.php
update_family_member_status.php
admin_page/brgy_record.php
admin_page/idps_user.php
modal/details_idps.php